name: build microservice-intelligence-action
on: [push]
jobs:
  main:
    name: build-${{ github.run_number }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}
      - uses: leanix/release-docker-image-action@master
      - uses: leanix/release-docker-image-action@master
        with:
          image: leanix/deployment-frequency-action
          path: deployment-frequency/


